// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stjajqqlfoamggczrbhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0amFqcXFsZm9hbWdnY3pyYmhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjM1NTUsImV4cCI6MjA3MzUzOTU1NX0.YqcWNytaJ4AyaTK50e9n8_4pLlZwQMPgMYSfxHItLgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});